import './globals.css'
import 'react-loading-skeleton/dist/skeleton.css'
import type { ReactNode } from 'react'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Open Movie',
  description: 'Generated by create next app'
}

const helveticaFont = localFont({
  src: [
    {
      path: '../../public/fonts/HelveticaNeue/HelveticaNeueLTStd-Lt.otf',
      weight: '300'
    },
    {
      path: '../../public/fonts/HelveticaNeue/HelveticaNeueLTStd-Roman.otf',
      weight: '400'
    },
    {
      path: '../../public/fonts/HelveticaNeue/HelveticaNeueLTStd-Md.otf',
      weight: '500'
    },
    {
      path: '../../public/fonts/HelveticaNeue/HelveticaNeueLTStd-Bd.otf',
      weight: '700'
    }
  ],
  variable: '--font-helvetica'
})

export default function RootLayout ({
  children
}: {
  children: ReactNode
}): JSX.Element {
  return (
    <html lang="en" className={`${helveticaFont.variable} font-sans`}>
      <body>{children}</body>
    </html>
  )
}
